#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "clouddisk.pb.h"

namespace clouddisk
{

namespace UserService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void SignUp(SignUpRequest *request, SignUpResponse *response,
					srpc::RPCContext *ctx) = 0;

	virtual void SignIn(SignUpRequest *request, SignUpResponse *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using SignUpDone = std::function<void (SignUpResponse *, srpc::RPCContext *)>;
using SignInDone = std::function<void (SignUpResponse *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void SignUp(const SignUpRequest *req, SignUpDone done);
	void SignUp(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> async_SignUp(const SignUpRequest *req);

	void SignIn(const SignUpRequest *req, SignInDone done);
	void SignIn(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> async_SignIn(const SignUpRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_SignUp_task(SignUpDone done);
	srpc::SRPCClientTask *create_SignIn_task(SignInDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void SignUp(const SignUpRequest *req, SignUpDone done);
	void SignUp(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> async_SignUp(const SignUpRequest *req);

	void SignIn(const SignUpRequest *req, SignInDone done);
	void SignIn(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> async_SignIn(const SignUpRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_SignUp_task(SignUpDone done);
	srpc::SRPCHttpClientTask *create_SignIn_task(SignInDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void SignUp(const SignUpRequest *req, SignUpDone done);
	void SignUp(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> async_SignUp(const SignUpRequest *req);

	void SignIn(const SignUpRequest *req, SignInDone done);
	void SignIn(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> async_SignIn(const SignUpRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_SignUp_task(SignUpDone done);
	srpc::BRPCClientTask *create_SignIn_task(SignInDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void SignUp(const SignUpRequest *req, SignUpDone done);
	void SignUp(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> async_SignUp(const SignUpRequest *req);

	void SignIn(const SignUpRequest *req, SignInDone done);
	void SignIn(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> async_SignIn(const SignUpRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_SignUp_task(SignUpDone done);
	srpc::TRPCClientTask *create_SignIn_task(SignInDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void SignUp(const SignUpRequest *req, SignUpDone done);
	void SignUp(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> async_SignUp(const SignUpRequest *req);

	void SignIn(const SignUpRequest *req, SignInDone done);
	void SignIn(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> async_SignIn(const SignUpRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_SignUp_task(SignUpDone done);
	srpc::TRPCHttpClientTask *create_SignIn_task(SignInDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("clouddisk.UserService")
{
	this->srpc::RPCService::add_method("SignUp",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::SignUp);
		});

	this->srpc::RPCService::add_method("SignIn",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::SignIn);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("clouddisk.UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("clouddisk.UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::SignUp(const SignUpRequest *req, SignUpDone done)
{
	auto *task = this->create_rpc_client_task("SignUp", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::SignUp(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignUp(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> SRPCClient::async_SignUp(const SignUpRequest *req)
{
	using RESULT = std::pair<SignUpResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignUpResponse>("SignUp", srpc::RPCAsyncFutureCallback<SignUpResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::SignIn(const SignUpRequest *req, SignInDone done)
{
	auto *task = this->create_rpc_client_task("SignIn", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::SignIn(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignIn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> SRPCClient::async_SignIn(const SignUpRequest *req)
{
	using RESULT = std::pair<SignUpResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignUpResponse>("SignIn", srpc::RPCAsyncFutureCallback<SignUpResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_SignUp_task(SignUpDone done)
{
	return this->create_rpc_client_task("SignUp", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_SignIn_task(SignInDone done)
{
	return this->create_rpc_client_task("SignIn", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("clouddisk/UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("clouddisk/UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::SignUp(const SignUpRequest *req, SignUpDone done)
{
	auto *task = this->create_rpc_client_task("SignUp", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::SignUp(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignUp(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_SignUp(const SignUpRequest *req)
{
	using RESULT = std::pair<SignUpResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignUpResponse>("SignUp", srpc::RPCAsyncFutureCallback<SignUpResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::SignIn(const SignUpRequest *req, SignInDone done)
{
	auto *task = this->create_rpc_client_task("SignIn", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::SignIn(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignIn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_SignIn(const SignUpRequest *req)
{
	using RESULT = std::pair<SignUpResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignUpResponse>("SignIn", srpc::RPCAsyncFutureCallback<SignUpResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_SignUp_task(SignUpDone done)
{
	return this->create_rpc_client_task("SignUp", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_SignIn_task(SignInDone done)
{
	return this->create_rpc_client_task("SignIn", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("clouddisk.UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("clouddisk.UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::SignUp(const SignUpRequest *req, SignUpDone done)
{
	auto *task = this->create_rpc_client_task("SignUp", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::SignUp(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignUp(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> BRPCClient::async_SignUp(const SignUpRequest *req)
{
	using RESULT = std::pair<SignUpResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignUpResponse>("SignUp", srpc::RPCAsyncFutureCallback<SignUpResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::SignIn(const SignUpRequest *req, SignInDone done)
{
	auto *task = this->create_rpc_client_task("SignIn", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::SignIn(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignIn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> BRPCClient::async_SignIn(const SignUpRequest *req)
{
	using RESULT = std::pair<SignUpResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignUpResponse>("SignIn", srpc::RPCAsyncFutureCallback<SignUpResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_SignUp_task(SignUpDone done)
{
	return this->create_rpc_client_task("SignUp", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_SignIn_task(SignInDone done)
{
	return this->create_rpc_client_task("SignIn", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("clouddisk.UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("clouddisk.UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::SignUp(const SignUpRequest *req, SignUpDone done)
{
	auto *task = this->create_rpc_client_task("/clouddisk.UserService/SignUp", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::SignUp(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignUp(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> TRPCClient::async_SignUp(const SignUpRequest *req)
{
	using RESULT = std::pair<SignUpResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignUpResponse>("/clouddisk.UserService/SignUp", srpc::RPCAsyncFutureCallback<SignUpResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::SignIn(const SignUpRequest *req, SignInDone done)
{
	auto *task = this->create_rpc_client_task("/clouddisk.UserService/SignIn", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::SignIn(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignIn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> TRPCClient::async_SignIn(const SignUpRequest *req)
{
	using RESULT = std::pair<SignUpResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignUpResponse>("/clouddisk.UserService/SignIn", srpc::RPCAsyncFutureCallback<SignUpResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_SignUp_task(SignUpDone done)
{
	auto *task = this->create_rpc_client_task("/clouddisk.UserService/SignUp", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_SignIn_task(SignInDone done)
{
	auto *task = this->create_rpc_client_task("/clouddisk.UserService/SignIn", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("clouddisk.UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("clouddisk.UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::SignUp(const SignUpRequest *req, SignUpDone done)
{
	auto *task = this->create_rpc_client_task("SignUp", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::SignUp(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignUp(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_SignUp(const SignUpRequest *req)
{
	using RESULT = std::pair<SignUpResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignUpResponse>("SignUp", srpc::RPCAsyncFutureCallback<SignUpResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::SignIn(const SignUpRequest *req, SignInDone done)
{
	auto *task = this->create_rpc_client_task("SignIn", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::SignIn(const SignUpRequest *req, SignUpResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_SignIn(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignUpResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_SignIn(const SignUpRequest *req)
{
	using RESULT = std::pair<SignUpResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignUpResponse>("SignIn", srpc::RPCAsyncFutureCallback<SignUpResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_SignUp_task(SignUpDone done)
{
	auto *task = this->create_rpc_client_task("SignUp", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_SignIn_task(SignInDone done)
{
	auto *task = this->create_rpc_client_task("SignIn", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace UserService

} // end namespace clouddisk

